# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(980, 599)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 991, 611))
        self.label.setStyleSheet("background-color: rgb(5, 6, 7);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"C:\\Users\\Jarvis\\Desktop\\JarvisFinal\\img\\jarvisBg.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 530, 75, 23))
        self.pushButton.setStyleSheet("\n""background-color: rgb(134, 239, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 391, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"C:\\Users\\Jarvis\\Desktop\\JarvisFinal\\img\\initialization.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 530, 75, 23))
        self.pushButton_2.setStyleSheet("\n""background-color: rgb(134, 239, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 510, 291, 81))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"C:\\Users\\Jarvis\\Desktop\\JarvisFinal\\img\\lableBg.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(690, 0, 291, 81))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(r"C:\\Users\\Jarvis\\Desktop\\JarvisFinal\\img\\lableBg.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 530, 251, 41))
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser.setStyleSheet("background:transparent;\n"
 "border-radius:none;\n""color:white;\n""font-size:20px")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 20, 251, 41))
        self.textBrowser_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
 "border-radius:none;\n""color:white;\n""font-size:20px")
        self.textBrowser_2.setObjectName("textBrowser_2")
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "Jarvis"))
        self.pushButton.setText(_translate("JarvisUi", "Run"))
        self.pushButton_2.setText(_translate("JarvisUi", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
